apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4fmy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-4fmy@sha256:41e806c62907390ece523e6e1015c9f94151ba3231ecf67d45dc8b4e9426fe90
        name: my-nodejs
        resources: {}
status: {}
